---
- name: "Import {{ name }} GPG key"
  rpm_key:
    key: "{{ gpg_url }}"
    state: present
  when: gpg_url is defined

# https://github.com/ansible/ansible/issues/10515
# Even with workarounds, it gives 'Not a valid key' errors, so copy first.
# Use 'package' for destination filename, as that should be unique.
- name: "Copy {{ name }} GPG key"
  copy:
    src: "{{ gpg_file }}"
    dest: "/etc/pki/rpm-gpg/{{ package }}"
    owner: root
    group: root
    mode: '0644'
  when: gpg_file is defined

# https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9
- include_role:
    name: bviktor.rpm_policy
  vars:
    policy: 'LEGACY'
  when: gpg_allow_sha1 is defined and gpg_allow_sha1|bool

- name: "Import {{ name }} GPG key"
  rpm_key:
    key: "/etc/pki/rpm-gpg/{{ package }}"
    state: present
  when: gpg_file is defined

- include_role:
    name: bviktor.rpm_policy
  vars:
    policy: 'DEFAULT'
  when: gpg_allow_sha1 is defined and gpg_allow_sha1|bool
