---
- include_tasks: gpg_el.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: gpg_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: repo.yml
- include_tasks: "{% if conflict is defined and conflict | length %}install_conflict.yml{% else %}install.yml{% endif %}"
- include_tasks: ldconfig.yml
