---
- include_tasks: gpg_el.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: gpg_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: repo.yml
- include_tasks: "{% if except is defined and except|length %}install_except.yml{% else %}install.yml{% endif %}"
- include_tasks: ldconfig.yml
