---
- include_tasks: gpg_el.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: gpg_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: repo.yml

- include_tasks: install_el.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: install_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: ldconfig.yml
